enum
{
	// string table definitions
	IDS_GRADIENTTITLE	= 10000,
	IDS_TYPE,
	IDS_INTERPOLATION,
	IDS_NONE,
	IDS_LINEAR,
	IDS_EXPUP,
	IDS_EXPDOWN,
	IDS_SMOOTH,
	IDS_POSITION,
	IDS_SPHERIZE,
	IDS_ROUNDED_TUBE,
	IDS_TRIANGULATE,
	IDS_GL_TEST_OBJECT,
	IDS_VIDEOPOST,
	IDS_ATOM,
	IDS_ATOM_POINT,
	IDS_ATOM_EDGE,
	IDS_CIRCLE,
	IDS_LISTVIEW,
	IDS_SERIAL_HOOK,

	IDS_LOOKATCAMERA,
	IDS_SIMPLEMATERIAL,
	IDS_FUNKY_GL_MATERIAL,
	IDS_PARTICLEVOLUME,
	IDS_MANDELBROT,
	IDS_SDKGRADIENT,
	IDS_BITMAPDISTORTION,
	IDS_BLINKER,
	IDS_GRAVITATION,

	IDS_BFF,
	IDS_STL,
	IDS_SCULPT,
	IDS_MENUTEST,
	IDS_ASYNCTEST,
	IDS_ACTIVEOBJECT,
	IDS_PGPTEST,

	IDC_SERIALNUMBER,
	DLG_REGISTER,

	IDS_PARTICLEVOLUME_HIGH_DENSITY,
	IDS_PARTICLEVOLUME_LOW_DENSITY,

	// IDs for the global string table
	IDS_APPLY_FILTER,
	IDS_THRESHOLD,
	IDS_MATRIX,

	// threshold dialog
	DLG_THRESHOLD,
	GADGET_THRESHOLD_SLIDER_LEVELS,
	GADGET_THRESHOLD_DOCUMENT_PREVIEW,
	GADGET_THRESHOLD_PREVIEWGROUP,

	// sample matrix dialog
	DLG_SMPL_MATRIX,
	GADGET_SMPL_MATRIX_SLIDER_MIX,
	GADGET_SMPL_MATRIX_SLIDER_ANGLE,
	GADGET_SMPL_MATRIX_DOCUMENT_PREVIEW,
	GADGET_SMPL_MATRIX_TEXTURE_MODE,
	GADGET_SMPL_MATRIX_TYPE_POPUP,
	GADGET_SMPL_MATRIX_PREVIEWGROUP,



	AOV_CLOUD_OUTPUT1,
	AOV_CLOUD_OUTPUT2,
	AOV_CLOUD_OUTPUT3,

	AOV_CLOUD_ADD,
	AOV_CLOUD_REMOVE,
	AOV_CLOUD_DUPLICATE,
	AOV_CLOUD_VIEW,
	AOV_CLOUD_SELECTOR_DIALOG,

	AOV_CLOUD_SELECTOR,
	CLOUD_BUTTON_OK,
	CLOUD_BUTTON_CANCEL,
	CLOUD_GADGET_ERASE,
	DL_CLOUD_AUXILIARY_COMPONENTS_LISTVIEW,
	DL_CLOUD_SHADING_COMPONENTS_LISTVIEW,
	DL_CLOUD_SELECTED_LAYERS_LISTVIEW,


	AOV_OUTPUT1,
	AOV_OUTPUT2,
	AOV_OUTPUT3,

	AOV_ADD,
	AOV_REMOVE,
	AOV_DUPLICATE,
	AOV_VIEW,
	AOV_SELECTOR_DIALOG,


	AOV_SELECTOR,
	MULTILIGHT_SELECTOR,
	BUTTON_OK,
	BUTTON_CANCEL,
	GADGET_ERASE,
	DL_AUXILIARY_COMPONENTS_LISTVIEW,
	DL_SHADING_COMPONENTS_LISTVIEW,
	DL_SELECTED_LAYERS_LISTVIEW,
	IDS_PRIMITIVETOOL,
	DL_MULTI_LIGHT_TREEVIEW,

	IDS_SUBDIALOG,
	DLG_SUBDIALOG,
	GADGET_SUBDIALOG,
	GADGET_SUB1,
	GADGET_SUB2,

	DLG_VIDEOPOST,
	IDS_VPINVERTIMAGE,
	IDS_MORPHMIXER,
	IDS_IMPORTFAILED,
	IDS_MORPHSELECT,
	IDS_VPVISUALIZE_CHANNEL,
	IDS_VPSTEREO,
	
	
	DL_MULTI_LIGHT_LISTVIEW,
	DL_DISPLAY_ALL_LIGHTS,
	DL_LIGHTS_REFRESH,
	
	
	IDS_VPVISUALIZEPOST,
	IDS_VPRECONSTRUCT,

	IDS_HLP_EDGECUT_SDK,
	IDS_EDGECUT_SDK,
	IDS_HLP_REVERSE_NORMALS_SDK,
	IDS_REVERSE_NORMALS_SDK,
	IDS_SCULPTING_TOOL,

	IDS_SCULPTDRAWPOLY_TOOL,
	IDS_SCULPTPULLBRUSH_TOOL,
	IDS_SCULPTCUBESBRUSH_TOOL,
	IDS_SCULPTBRUSH_SELECTIONTOOL,
	IDS_SCULPTGRABBRUSH_TOOL,
	IDS_SCULPTDRAWPOLYBRUSH_TOOL,
	IDS_SCULPTBRUSH_SPLINETOOL,

	IDS_PICKOBJECT_SDK,
	IDS_HELP_PICKOBJECT_SDK,

	IDS_LAYER_SHADER_BROWSER,

	// Dialog definitions of IDD_SHADER_BROWSER start here
	IDD_SHADER_BROWSER,
	IDC_LAYER_BROWSER_LINK,
	IDC_LAYER_BROWSER_TREE,
	IDC_LAYER_BROWSER_PROPS,
	// Dialog definitions of IDD_SHADER_BROWSER end here

	// Falloff types
	IDS_RANDOMFALLOFF,

	// Effectors
	IDS_NOISEEFFECTOR,
	IDS_DROPEFFECTOR,

	// Hair

	IDS_HAIR_DEFOMER_EXAMPLE,
	IDS_HAIR_FORCE_EXAMPLE,
	IDS_HAIR_COLLIDER_EXAMPLE,
	IDS_HAIR_CONSTRAINT_EXAMPLE,
	IDS_HAIR_GRASS_EXAMPLE,
	IDS_HAIR_SHADER_EXAMPLE,
	IDS_HAIR_VIDEOPOST_EXAMPLE,
	IDS_HAIR_STYLING_EXAMPLE,
	IDS_HAIR_RENDERING_EXAMPLE,
	IDS_HAIR_GENERATOR_EXAMPLE,

	IDS_SCULPT_DEFORMER,
	IDS_SCULPT_BRUSH_EXAMPLE_MODIFIER,
	IDS_SCULPT_BRUSH_TWIST,
	IDS_SCULPT_BRUSH_MULTISTAMP,
	IDS_PAINT_BRUSH_BASE,
	IDS_PAINT_BRUSH_SCULPT,
	IDS_PAINT_BRUSH_BASE_HELP,
	IDS_PAINT_BRUSH_SCULPT_HELP,

	// Other

	IDS_NULLSNAP,
	IDS_CUSTOMGUISTRING,
	IDS_CUSTOMGUI_DOTS,
	IDS_CUSTOMDATATYPE_DOTS,

	IDS_EXAMPLEDIALOG_COMMAND,
	IDS_OBJECTDATA_DESCRIPTION,

	IDS_OBJECTDATA_GETSETDPARAMETEREXAMPLE,
	
	
// End of symbol definition
	_DUMMY_ELEMENT_
};
