#ifndef MDELIGHTMATERIAL_H__
#define MDELIGHTMATERIAL_H__

enum
{
	MATERIAL_COLOR		= 3000,
	MATERIAL_MAT_PREVIEW, 
	SURFACE_PAGE,
	GROUP_SURFACE,
	SURFACE_LINK,
	DISPLACEMENT_PAGE,
	GROUP_DISPLACEMENT,
	DISPLACEMENT_LINK,
	DISPLACEMENT_BOUND
};

#endif 
