CONTAINER Xglassshader
{
	NAME Xglassshader;

	GROUP SHADER_GROUP
	{
		DEFAULT 1;
		COLOR REFLECTION_COLOR{}
		COLOR REFRACTION_COLOR{}
		SEPARATOR { LINE; }
		REAL ROUGHNESS{UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		SHADERLINK ROUGHNESS_SHADER {ANIM OFF;}
		SEPARATOR { LINE; }
		REAL IOR{MIN 0;}
		SEPARATOR { LINE; }
		LONG MODE{
			CYCLE {
				MODE_REFRACTION;
				MODE_OPACITY;
			}
		}
}

	}

}