CONTAINER Tcamera
{
	NAME Tcamera;
	INCLUDE Tbase;
	
	GROUP ID_TAGPROPERTIES
	{
		REAL SHUTTER_ANGLE		{UNIT PERCENT; MIN 0.0;ANIM OFF;}
		REAL SHUTTER_OPENING_EFFICIENCY	{UNIT PERCENT; MIN 0.0; MAX 100.0;ANIM OFF;}	
		REAL SHUTTER_CLOSING_EFFICIENCY	{UNIT PERCENT; MIN 0.0; MAX 100.0;ANIM OFF;}

		SEPARATOR{ LINE;}
		
		BOOL ENABLE_DOF{}
		REAL F_STOP{MIN 0.0;}
		
		BOOL FINITE_BLADES{}
		LONG NUMBER_OF_BLADES{MIN 3;}
		REAL ROTATION{UNIT DEGREE; MIN 0; MAX 360;}		
	}
	
	
}
