CONTAINER vprendersettings
{
	NAME vprendersettings;
	INCLUDE VPbase;

	GROUP DL_GROUP_QUALITY{
		//LONG DL_GENERAL_MODE{ANIM OFF; CYCLE{
		//	DL_MODE_SCANLINE; 
		//	DL_MODE_RAYTRACER; 
		//	DL_MODE_PROGRESSIVE;}
		//}
		//SEPARATOR { LINE; }
		//REAL DL_SHADINGRATE		{ MIN 0; ANIM OFF;}
  		//SEPARATOR { LINE; }
		LONG 	DL_SHADING_SAMPLES{MIN 0; ANIM OFF;}
		//BOOL DL_RAYCACHE{ANIM OFF;}
		SEPARATOR{LINE;}
		LONG DL_PIXELSAMPLES	{ MIN 1; ANIM OFF;}
		//LONG DL_PIXELSAMPLES_Y	{ MIN 1; ANIM OFF;}	
		//SEPARATOR { LINE; }
		LONG DL_PIXELFILTER		{ANIM OFF;
			CYCLE{
				DL_FILTER_SINC;
				DL_FILTER_BOX;
				DL_FILTER_TRIANGLE;
				DL_FILTER_CATMULL_ROM;
				DL_FILTER_MITCHELL;
				DL_FILTER_BLACKMANN_HARRIS;
				DL_FILTER_BESSEL;
				DL_FILTER_GAUSSIAN;
			}
		}
		//REAL DL_FILTERWIDTH		{MIN 1.0; ANIM OFF;}
		
		SEPARATOR{LINE;}
		BOOL DL_USE_MOTION_BLUR		{ ANIM OFF;}
		LONG DL_MOTION_SAMPLES	{ MIN 1; ANIM OFF;}
		SEPARATOR{LINE;}
		LONG DL_MAX_REFLECTION_DEPTH{MIN 1; ANIM OFF;}
		LONG DL_MAX_REFRACTION_DEPTH{MIN 1; ANIM OFF;}
		LONG DL_MAX_DIFFUSE_DEPTH{MIN 1; ANIM OFF;}
		//SEPARATOR{LINE;}
		//REAL DL_TRACE_BIAS{MIN 0.0;ANIM OFF;}

	}
	GROUP DL_GROUP_OUTPUT{
		LONG DL_RENDERMODE		{ANIM OFF;
			CYCLE{
				DL_MODE_DIRECT;
				DL_MODE_STREAM;
				}
		}
		FILENAME DL_OUTPUTFILE {SAVE; ANIM OFF;}
		//BOOL DL_RIBOUT{ANIM OFF;}
		//BOOL DL_SHOW_IMAGE{ANIM OFF;}	
		//BOOL DL_SAVE_IMAGE{ANIM OFF;}	
		SEPARATOR{LINE;}
		
		BOOL DL_SHOW_IMAGE{ANIM OFF;}	
			
	}	

	GROUP DL_GROUP_CAMERA
	{
		
		//LONG DL_TRANSFORMATION_SAMPLES	{ MIN 1; ANIM OFF;}
		//LONG DL_DEFORMATION_SAMPLES		{ MIN 1; ANIM OFF;}	
		
		//SEPARATOR { LINE; }
		
		REAL DL_SHUTTER_ANGLE		{UNIT PERCENT; MIN 0.0;ANIM OFF;}
		REAL DL_SHUTTER_OPENING_EFFICIENCY	{UNIT PERCENT; MIN 0.0; MAX 100.0;ANIM OFF;}	
REAL DL_SHUTTER_CLOSING_EFFICIENCY	{UNIT PERCENT; MIN 0.0; MAX 100.0;ANIM OFF;}	
	}
	//GROUP DL_GROUP_RAYTRACING
	//{
	
		
	//	SEPARATOR{LINE;}
		
		
	//	SEPARATOR { LINE; }

		
		//BOOL DL_RAYCACHE{}
	//}
	//GROUP DL_GROUP_LWF
	//{
	//	REAL DL_GAMMA	{MIN 0.0;ANIM OFF;}

	//}
}
