#ifndef _Olightcard_H_
#define _Olightcard_H_

enum
{
	LIGHTCARD_WIDTH			= 1000,
	LIGHTCARD_HEIGHT,			
	LIGHTCARD_COLOR,		
	LIGHTCARD_INTENSITY,	
	LIGHTCARD_EXPOSURE,
	LIGHTCARD_SPREAD,	
	LIGHTCARD_SAMPLES,		
	LIGHTCARD_TEXTURE,	
	LIGHTCARD_ALPHA,	
	LIGHTCARD_SEEN_BY_CAMERA	
};

#endif