#pragma once
enum
{
	Shader_Path = 0,
	SHADER_GROUP = 100,
	INPUT_COLOR,
	INPUT_COLOR_SHADER,
	
	VARIATION,
	VARIATION_HUE,
	VARIATION_HUE_SHADER,
	VARIATION_SATURATION,
	VARIATION_SATURATION_SHADER,
	VARIATION_BRIGHTNESS,
	VARIATION_BRIGHTNESS_SHADER,
	RANDOM,
	RANDOMNESS_TYPE,
	RANDOMNESS_UNIFORM=0,
	RANDOMNESS_NATUAL=1,
	SOURCE_TYPE=30,
	SOURCE_TYPE_OBJECT=0,
	SOURCE_TYPE_MATERIAL=1,
	SEED=40,
	DUMB_VALUE
};

