#pragma once
enum
{
	Shader_Path = 0,
	SHADER_GROUP = 100,
	INPUT_COLOR,
	INPUT_COLOR_SHADER,
	INPUT_MASK,
	INPUT_MASK_SHADER,

	CORRECTION,
	CORRECTION_GAMMA,
	EMPTY1,
	CORRECTION_GAMMA_SHADER,
	CORRECTION_HUE_SHIFT,
	CORRECTION_HUE_SHIFT_SHADER,
	CORRECTION_SATURATION,
	CORRECTION_SATURATION_SHADER,
	CORRECTION_VIBRANCE,
	CORRECTION_VIBRANCE_SHADER,
	EMPTY2,
	CORRECTION_CONSTRAST,
	CORRECTION_CONSTRAST_SHADER,
	CORRECTION_CONSTRAST_PIVOT,
	CORRECTION_CONSTRAST_PIVOT_SHADER,
	EMPTY3,
	CORRECTION_EXPOSURE,
	CORRECTION_EXPOSURE_SHADER,
	CORRECTION_GAIN,
	CORRECTION_GAIN_SHADER,
	CORRECTION_OFFSET,
	CORRECTION_OFFSET_SHADER,
	CORRECTION_INVERT,
	DUMB_VALUE
};

