CONTAINER dl_car_paint
{
	NAME dl_car_paint;
	
	INCLUDE Mpreview;
	INCLUDE Mbase;
	
	GROUP Obaselist
	{
		BOOL COATING_PAGE { HIDDEN; PAGE; PARENTMSG COATING_LAYER; }
		BOOL FLAKES_PAGE { HIDDEN; PAGE; PARENTMSG FLAKES; }
		BOOL BASE_PAGE { HIDDEN; PAGE; PARENTMSG BASE_LAYER; }
		BOOL BUMP_PAGE { HIDDEN; PAGE; PARENTMSG BUMP; }
	}
	
	GROUP COATING_LAYER
	{
		REAL COATING_LAYER_THICKNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK COATING_LAYER_THICKNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		COLOR COATING_LAYER_COLOR{}
		SHADERLINK COATING_LAYER_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		REAL COATING_LAYER_ROUGHNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK COATING_LAYER_ROUGHNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL COATING_LAYER_SPECULAR_LEVEL{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK COATING_LAYER_SPECULAR_LEVEL_SHADER{ANIM OFF;}
	}
	
	GROUP FLAKES
	{
		REAL FLAKES_DENSITY{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK FLAKES_DENSITY_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		COLOR FLAKES_COLOR{}
		SHADERLINK FLAKES_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL FLAKES_ROUGHNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK FLAKES_ROUGHNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL FLAKES_SCALE{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK FLAKES_SCALE_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL FLAKES_RANDOMNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK FLAKES_RANDOMNESS_SHADER{ANIM OFF;}
	}
	
	GROUP BASE_LAYER
	{
		COLOR BASE_LAYER_COLOR{}
		SHADERLINK BASE_LAYER_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL BASE_LAYER_ROUGHNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK BASE_LAYER_ROUGHNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL BASE_LAYER_SPECULAR_LEVEL{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK BASE_LAYER_SPECULAR_LEVEL_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL BASE_LAYER_METALLIC{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK BASE_LAYER_METALLIC_SHADER{ANIM OFF;}
	}
	
	GROUP BUMP
	{
		LONG BUMP_TYPE
		{
			CYCLE
			{
				BUMP_MAP;
				NORMAL_MAP_DIRECTX;
				NORMAL_MAP_OPENGL;
				DISPLACEMENT_0;
				DISPLACEMENT_5;
			}
		}
		SHADERLINK BUMP_VALUE{ANIM OFF;}
		SEPARATOR { LINE; }
		REAL BUMP_INTENSITY{ANIM OFF; CUSTOMGUI REALSLIDER;}
		LONG BUMP_LAYERS_AFFECTED
		{
			CYCLE
			{
				AFFECT_BOTH_LAYERS;
				AFFECT_COATING_LAYER;
				AFFECT_BASE_LAYER;
			}
		}
	}
	
	INCLUDE Massign;

}