#pragma once
enum
{
	Shader_Path = 0,
	SHADER_GROUP =100,
	BLEND_MODE,
	BLEND_MODE_OVER=0,
	BLEND_MODE_DARKEN,
	BLEND_MODE_COLOR_BURN,
	BLEND_MODE_ADD,
	BLEND_MODE_SCREEN,
	BLEND_MODE_LIGHTEN,
	BLEND_MODE_COLOR_DODGE,
	BLEND_MODE_OVERLAY,
	BLEND_MODE_SOFT_LIGHT,
	BLEND_MODE_HARD_LIGHT,
	BLEND_MODE_ADD_SUBTRACT,
	BLEND_MODE_SUBTRACT,
	BLEND_MODE_DIFFERENCE,
	BLEND_MODE_DIVIDE,
	BLEND_MODE_HUE,
	BLEND_MODE_SATURATION,
	BLEND_MODE_COLOR,
	BLEND_MODE_LUMINOSITY,
	
	BLEND_FACTOR=30,
	BLEND_FACTOR_SHADER,
	BLEND_EMPTY,
	BLEND_FOREGROUND,
	BLEND_FOREGROUND_SHADER,
	BLEND_BACKGROUND,
	BLEND_BACKGROUND_SHADER,
	DUMB_VALUE
};

