CONTAINER dl_color_blend
{
	NAME dl_color_blend;

	GROUP SHADER_GROUP
	{
		
		LONG BLEND_MODE
		{
			ANIM OFF;
			CYCLE
			{
				BLEND_MODE_OVER;
				BLEND_MODE_DARKEN;
				BLEND_MODE_COLOR_BURN;
				BLEND_MODE_ADD;
				BLEND_MODE_SCREEN;
				BLEND_MODE_LIGHTEN;
				BLEND_MODE_COLOR_DODGE;
				BLEND_MODE_OVERLAY;
				BLEND_MODE_SOFT_LIGHT;
				BLEND_MODE_HARD_LIGHT;
				BLEND_MODE_ADD_SUBTRACT;
				BLEND_MODE_SUBTRACT;
				BLEND_MODE_DIFFERENCE;
				BLEND_MODE_DIVIDE;
				BLEND_MODE_HUE;
				BLEND_MODE_SATURATION;
				BLEND_MODE_COLOR;
				BLEND_MODE_LUMINOSITY;
			}
		}
		
		REAL BLEND_FACTOR{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK BLEND_FACTOR_SHADER{ANIM OFF;}
		STATICTEXT BLEND_EMPTY{ANIM OFF;}
		COLOR BLEND_FOREGROUND{ANIM OFF;}
		SHADERLINK BLEND_FOREGROUND_SHADER{ANIM OFF;}
		
		COLOR BLEND_BACKGROUND{ANIM OFF;}		
		SHADERLINK BLEND_BACKGROUND_SHADER{ANIM OFF;}
	}
}