CONTAINER dl_flakes
{
	NAME dl_flakes;

	GROUP SHADER_GROUP
	{
		REAL FLAKES_DENSITY{MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		SHADERLINK FLAKES_DENSITY_SHADER{ANIM OFF;}
		REAL FLAKES_SCALE{MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		SHADERLINK FLAKES_SCALE_SHADER{ANIM OFF;}
		REAL FLAKES_RANDOMNESS{MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		SHADERLINK FLAKES_RANDOMNESS_SHADER{ANIM OFF;}
		LONG FLAKES_LAYERS{MIN 1; MINSLIDER 1; MAXSLIDER 8; STEP 1; CUSTOMGUI LONGSLIDER;}			
	}
}

