CONTAINER dl_facing_ratio
{
	NAME dl_facing_ratio;

	GROUP
	{
		GROUP SHADER_GROUP
		{
			DEFAULT 1;
			COLOR FACING_RATIO_COLOR_EDGE{ANIM OFF;}
			SHADERLINK FACING_RATIO_COLOR_EDGE_SHADER{ANIM OFF;}
			
			COLOR FACING_RATIO_COLOR_CENTER{ANIM OFF;}
			SHADERLINK FACING_RATIO_COLOR_CENTER_SHADER{ANIM OFF;}
			
			REAL FACING_RATIO_BIAS{}
			SHADERLINK FACING_RATIO_BIAS_SHADER{ANIM OFF;}
			
			REAL FACING_RATIO_CONTRAST{}
			SHADERLINK FACING_RATIO_CONTRAST_SHADER{ANIM OFF;}
			
		}
			
		GROUP BUMP
		{	
			DEFAULT 1;
			LONG BUMP_TYPE
			{
				CYCLE
				{
					BUMP_MAP;
					NORMAL_MAP_DIRECTX;
					NORMAL_MAP_OPENGL;
					DISPLACEMENT_0;
					DISPLACEMENT_5;
				}
			}
			SHADERLINK BUMP_VALUE{ANIM OFF;}
			SEPARATOR { LINE; }
			REAL BUMP_INTENSITY{ANIM OFF; CUSTOMGUI REALSLIDER;}
		}
	}
}