#pragma once
enum
{
	Shader_Path = 0,
	SHADER_GROUP = 100,
	FACING_RATIO_COLOR_EDGE,
	FACING_RATIO_COLOR_EDGE_SHADER,
	FACING_RATIO_COLOR_CENTER,
	FACING_RATIO_COLOR_CENTER_SHADER,
	FACING_RATIO_BIAS,
	FACING_RATIO_BIAS_SHADER,
	FACING_RATIO_CONTRAST,
	FACING_RATIO_CONTRAST_SHADER,
	
	BUMP_PAGE,
	BUMP,
	BUMP_TYPE,
		BUMP_MAP=0,
		NORMAL_MAP_DIRECTX=1,
		NORMAL_MAP_OPENGL=2,
		DISPLACEMENT_0=3,
		DISPLACEMENT_5=4,
	BUMP_VALUE = 200,
	BUMP_INTENSITY,
	DUMB_VALUE
};

