#pragma once

enum
{
	Shader_Path = 0,
	REFLECTION_PAGE=100,
	REFLECTION,
	REFLECTION_COLOR,
	REFLECTION_COLOR_SHADER,
	REFLECTION_ROUGHNESS,
	REFLECTION_ROUGHNESS_SHADER,
	REFLECTION_IOR,
	REFLECTION_IOR_SHADER,
	REFLECTION_THIN_FILM,
	REFLECTION_FILM_THICKNESS,
	REFLECTION_FILM_THICKNESS_SHADER,
	REFLECTION_FILM_IOR,
	REFLECTION_FILM_IOR_SHADER,

	REFRACTION_PAGE,
	REFRACTION,
	REFRACTION_COLOR,
	REFRACTION_COLOR_SHADER,
	REFRACTION_ROUGHNESS,
	REFRACTION_ROUGHNESS_SHADER,
	REFRACTION_IOR,
	REFRACTION_IOR_SHADER,
	
	VOLUMETRIC_PAGE,
	VOLUMETRIC,
	VOLUMETRIC_ENABLE,
	VOLUMETRIC_DENSITY,
	VOLUMETRIC_SCATTERING,
	VOLUMETRIC_TRANSPARENCY,
	
	INCADESCENCE_PAGE,
	INCADESCENCE,
	INCADESCENCE_COLOR,
	INCADESCENCE_COLOR_SHADER,
	INCADESCENCE_INTENSITY,
	
	BUMP_PAGE,
	BUMP,
	BUMP_TYPE,
		BUMP_MAP=0,
		NORMAL_MAP_DIRECTX=1,
		NORMAL_MAP_OPENGL=2,
		DISPLACEMENT_0=3,
		DISPLACEMENT_5=4,
	BUMP_VALUE = 200,
	BUMP_INTENSITY,
	DUMP_VALUE
	
};
