CONTAINER dl_hair_and_fur
{
	NAME dl_hair_and_fur;

	INCLUDE Mpreview;
	INCLUDE Mbase;
	


	GROUP Obaselist
	{
		BOOL HAIR_COLOR_PAGE { HIDDEN; PAGE; PARENTMSG HAIR_COLOR; }
		BOOL HAIR_LOOK_PAGE { HIDDEN; PAGE; PARENTMSG HAIR_LOOK; }
		BOOL HAIR_VARIATION_PAGE { HIDDEN; PAGE; PARENTMSG HAIR_VARIATION; }
		BOOL HAIR_BOOST_PAGE { HIDDEN; PAGE; PARENTMSG HAIR_BOOST; }
	}
	
	
	
	GROUP HAIR_COLOR
	{
		

		REAL HAIR_COLOR_MELANIN{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_COLOR_MELANIN_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL HAIR_COLOR_MELANIN_RED{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_COLOR_MELANIN_RED_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		COLOR HAIR_COLOR_DYE{}
		SHADERLINK HAIR_COLOR_DYE_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }		
		
		REAL HAIR_COLOR_DYE_WEIGHT{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_COLOR_DYE_WEIGHT_SHADER{ANIM OFF;}
	}
	
	GROUP HAIR_LOOK
	{
		REAL HAIR_LOOK_REFLECTIVITY{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_LOOK_REFLECTIVITY_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
			
		REAL HAIR_LOOK_ROUGHNESS_ALONG{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_LOOK_ROUGHNESS_ALONG_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
					
		REAL HAIR_LOOK_ROUGHNESS_AROUND{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_LOOK_ROUGHNESS_AROUND_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
							
		REAL HAIR_LOOK_SYNTHETIC_FIBER{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_LOOK_SYNTHETIC_FIBER_SHADER{ANIM OFF;}
	}
	
	GROUP HAIR_VARIATION
	{
		REAL HAIR_VARIATION_MELANIN{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_VARIATION_MELANIN_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL HAIR_VARIATION_MELANIN_RED{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_VARIATION_MELANIN_RED_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }		
		
		REAL HAIR_VARIATION_WHITE_HAIR{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_VARIATION_WHITE_HAIR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
				
		REAL HAIR_VARIATION_DYE_HUE{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_VARIATION_DYE_HUE_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
						
		REAL HAIR_VARIATION_DYE_SATURATION{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_VARIATION_DYE_SATURATION_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
								
		REAL HAIR_VARIATION_DYE_VALUE{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_VARIATION_DYE_VALUE_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
										
		REAL HAIR_VARIATION_ROUGHNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_VARIATION_ROUGHNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
												
		REAL HAIR_VARIATION_REFLECTIVITY{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_VARIATION_REFLECTIVITY_SHADER{ANIM OFF;}
	}
	
	GROUP HAIR_BOOST
	{
		REAL HAIR_BOOST_GLOSSINESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_BOOST_GLOSSINESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL HAIR_BOOST_REFLECTION{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_BOOST_REFLECTION_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
				
		REAL HAIR_BOOST_TRANSMISSION{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK HAIR_BOOST_TRANSMISSION_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
	}


	//INCLUDE Millum;
	INCLUDE Massign;
}
