CONTAINER dl_metal
{
	NAME dl_metal;
	
	INCLUDE Mpreview;
	INCLUDE Mbase;
	
	GROUP Obaselist
	{
		BOOL COATING_PAGE { HIDDEN; PAGE; PARENTMSG COATING_LAYER; }
		BOOL METAL_PAGE { HIDDEN; PAGE; PARENTMSG METAL_LAYER; }
		BOOL BUMP_PAGE { HIDDEN; PAGE; PARENTMSG BUMP; }
	
	}
	
	GROUP COATING_LAYER
	{
		REAL COATING_LAYER_THICKNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK COATING_LAYER_THICKNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		COLOR COATING_LAYER_COLOR{}
		SHADERLINK COATING_LAYER_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		REAL COATING_LAYER_ROUGHNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK COATING_LAYER_ROUGHNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL COATING_LAYER_SPECULAR_LEVEL{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK COATING_LAYER_SPECULAR_LEVEL_SHADER{ANIM OFF;}
	}

	GROUP METAL_LAYER
	{
		COLOR METAL_LAYER_COLOR{}
		SHADERLINK METAL_LAYER_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		COLOR METAL_LAYER_EDGE_COLOR{}
		SHADERLINK METAL_LAYER_EDGE_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL METAL_LAYER_ROUGHNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK METAL_LAYER_ROUGHNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		REAL METAL_LAYER_ANISOTROPY{MIN -1; MAX 1; MINSLIDER -1; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK METAL_LAYER_ANISOTROPY_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		COLOR METAL_LAYER_ANISOTROPY_DIRECTION{}
		SHADERLINK METAL_LAYER_ANISOTROPY_DIRECTION_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL METAL_LAYER_OPACITY{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK METAL_LAYER_OPACITY_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		BOOL METAL_LAYER_TEMPERED_METAL{}
			
		REAL METAL_LAYER_OXIDE_THICKNESS{MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK METAL_LAYER_OXIDE_THICKNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }		
		
		REAL METAL_LAYER_OXIDE_IOR{MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK METAL_LAYER_OXIDE_IOR_SHADER{ANIM OFF;}
	}
	
	GROUP BUMP
	{
		LONG BUMP_TYPE
		{
			CYCLE
			{
				BUMP_MAP;
				NORMAL_MAP_DIRECTX;
				NORMAL_MAP_OPENGL;
				DISPLACEMENT_0;
				DISPLACEMENT_5;
			}
		}
		
		REAL BUMP_INTENSITY{ANIM OFF; CUSTOMGUI REALSLIDER;}
		LONG BUMP_LAYERS_AFFECTED
		{
			CYCLE
			{
				AFFECT_BOTH_LAYERS;
				AFFECT_COATING_LAYER;
				AFFECT_BASE_LAYER;
			}
		}
	}
	
	INCLUDE Massign;

}