CONTAINER dl_principled
{
	NAME dl_principled;
	
	INCLUDE Mpreview;
	INCLUDE Mbase;
	
	GROUP Obaselist
	{
		BOOL COATING_PAGE { HIDDEN; PAGE; PARENTMSG COATING_LAYER; }
		BOOL BASE_PAGE { HIDDEN; PAGE; PARENTMSG BASE_LAYER; }
		BOOL SUBSURFACE_PAGE { HIDDEN; PAGE; PARENTMSG SUBSURFACE; }
		BOOL INCADESCENCE_PAGE { HIDDEN; PAGE; PARENTMSG INCADESCENCE; }
		BOOL BUMP_PAGE { HIDDEN; PAGE; PARENTMSG BUMP; }
	}
	
	GROUP COATING_LAYER
	{
		REAL COATING_LAYER_THICKNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK COATING_LAYER_THICKNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		COLOR COATING_LAYER_COLOR{}
		SHADERLINK COATING_LAYER_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		REAL COATING_LAYER_ROUGHNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK COATING_LAYER_ROUGHNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL COATING_LAYER_SPECULAR_LEVEL{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK COATING_LAYER_SPECULAR_LEVEL_SHADER{ANIM OFF;}
	}
	
	GROUP BASE_LAYER
	{
		COLOR BASE_LAYER_COLOR{}
		SHADERLINK BASE_LAYER_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL BASE_LAYER_ROUGHNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK BASE_LAYER_ROUGHNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL BASE_LAYER_SPECULAR_LEVEL{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK BASE_LAYER_SPECULAR_LEVEL_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL BASE_LAYER_METALLIC{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK BASE_LAYER_METALLIC_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		REAL BASE_LAYER_ANISOTROPY{MIN -1; MAX 1; MINSLIDER -1; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK BASE_LAYER_ANISOTROPY_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		COLOR BASE_LAYER_ANISOTROPY_DIRECTION{}
		SHADERLINK BASE_LAYER_ANISOTROPY_DIRECTION_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL BASE_LAYER_OPACITY{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK BASE_LAYER_OPACITY_SHADER{ANIM OFF;}
	}
	
	GROUP SUBSURFACE
	{
		BOOL USE_SUBSURFACE{}
		COLOR SUBSURFACE_COLOR{}
		SHADERLINK SUBSURFACE_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL SUBSURFACE_SCALE{MIN 1; MAX 1000; MINSLIDER 1; MAXSLIDER 500; STEP 1; CUSTOMGUI REALSLIDER;}
		SHADERLINK SUBSURFACE_SCALE_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL SUBSURFACE_IOR{MIN 1; MAX 5; MINSLIDER 1; MAXSLIDER 5; STEP 0.025; CUSTOMGUI REALSLIDER;}
		SHADERLINK SUBSURFACE_IOR_SHADER{ANIM OFF;}
	}
	
	GROUP INCADESCENCE
	{
		COLOR INCADESCENCE_COLOR{}
		SHADERLINK INCADESCENCE_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL INCADESCENCE_INTENSITY{MIN 0; MINSLIDER 0	; MAXSLIDER 100; STEP 1; CUSTOMGUI REALSLIDER;}
	}
	
	GROUP BUMP
	{
		LONG BUMP_TYPE
		{
			CYCLE
			{
				BUMP_MAP;
				NORMAL_MAP_DIRECTX;
				NORMAL_MAP_OPENGL;
				DISPLACEMENT_0;
				DISPLACEMENT_5;
			}
		}
		SHADERLINK BUMP_VALUE{ANIM OFF;}
		SEPARATOR { LINE; }
		REAL BUMP_INTENSITY{ANIM OFF; CUSTOMGUI REALSLIDER;}
		LONG BUMP_LAYERS_AFFECTED
		{
			CYCLE
			{
				AFFECT_BOTH_LAYERS;
				AFFECT_COATING_LAYER;
				AFFECT_BASE_LAYER;
			}
		}
	}
	
	INCLUDE Massign;

}