#pragma once
enum
{
	Shader_Path = 0,
	SHADER_GROUP = 100,
	INPUT_COLOR1,
	INPUT_COLOR1_SHADER,
	INPUT_IMPORTANCE1,
	INPUT_IMPORTANCE1_SHADER,
	EMPTY1,
	INPUT_COLOR2,
	INPUT_COLOR2_SHADER,
	INPUT_IMPORTANCE2,
	INPUT_IMPORTANCE2_SHADER,
	EMPTY2,
	INPUT_COLOR3,
	INPUT_COLOR3_SHADER,
	INPUT_IMPORTANCE3,
	INPUT_IMPORTANCE3_SHADER,
	EMPTY3,
	INPUT_COLOR4,
	INPUT_COLOR4_SHADER,
	INPUT_IMPORTANCE4,
	INPUT_IMPORTANCE4_SHADER,
	EMPTY4,
	INPUT_COLOR5,
	INPUT_COLOR5_SHADER,
	INPUT_IMPORTANCE5,
	INPUT_IMPORTANCE5_SHADER,
	INPUT,
	SEED,
	DUMMY
};

