#pragma once
enum
{
	Shader_Path = 0,
	
	SUBSTANCE_PAGE=100,
	MAIN_GROUP,
	MAIN_GROUP_PAGE,
	SUBSTANCE,
	SUBSTANCE_COLOR,
	SUBSTANCE_COLOR_SHADER,
	SUBSTANCE_ROUGHNESS,
	SUBSTANCE_ROUGHNESS_SHADER,
	SUBSTANCE_SPECULAR_LEVEL,
	SUBSTANCE_SPECULAR_LEVEL_SHADER,
	SUBSTANCE_METALLIC,
	SUBSTANCE_METALLIC_SHADER,	
	SUBSTANCE_OPACITY,
	SUBSTANCE_OPACITY_SHADER,

	EMISSIVE_PAGE,
	EMISSIVE,
	EMISSIVE_COLOR,
	EMISSIVE_COLOR_SHADER,
	EMISSIVE_INTENSITY,
	
	BUMP_PAGE,
	BUMP,
	BUMP_TYPE,
		BUMP_MAP=0,
		NORMAL_MAP_DIRECTX=1,
		NORMAL_MAP_OPENGL=2,
		DISPLACEMENT_0=3,
		DISPLACEMENT_5=4,
	BUMP_VALUE = 200,
	BUMP_INTENSITY,
	
	ASSIGNTEXTURE,
	ASSIGNTEXTURE_PAGE, 
	ASSIGN_TEXTURES,
	ROW1,
	ROW2,
	ROW3,
	EMPTY,
	EMPTY1,
	EMPTY2,
	EMPTYSPACE,
	EMPTYSPACE2,
	EMPTYSPACE3,
	EMPTYSPACE4,

	DUMP_VALUE
	
};
