CONTAINER dl_skin	
{
	NAME dl_skin;
	
	INCLUDE Mpreview;
	INCLUDE Mbase;
	
	GROUP Obaselist
	{
		BOOL SKIN_PAGE { HIDDEN; PAGE; PARENTMSG SKIN; }
		BOOL SUBSURFACE_PAGE { HIDDEN; PAGE; PARENTMSG SUBSURFACE; }
		BOOL BUMP_PAGE { HIDDEN; PAGE; PARENTMSG BUMP; }
	}
	
	GROUP SKIN
	{
		COLOR SKIN_COLOR{}
		SHADERLINK SKIN_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		REAL SKIN_ROUGHNESS{MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK SKIN_ROUGHNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL SKIN_SPECULAR_LEVEL{MIN 0; MINSLIDER 0; MAXSLIDER 100; STEP 0.001; CUSTOMGUI REALSLIDER;}
		SHADERLINK SKIN_SPECULAR_LEVEL_SHADER{ANIM OFF;}		
	}
	
	GROUP SUBSURFACE
	{
		COLOR SUBSURFACE_COLOR{}
		SHADERLINK SUBSURFACE_COLOR_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }

		REAL SUBSURFACE_SCALE{MIN 1; MAX 1000; MINSLIDER 1; MAXSLIDER 500; STEP 1; CUSTOMGUI REALSLIDER;}
		SHADERLINK SUBSURFACE_SCALE_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		
		REAL SUBSURFACE_IOR{MIN 1; MAX 5; MINSLIDER 1; MAXSLIDER 5; STEP 0.025; CUSTOMGUI REALSLIDER;}
		SHADERLINK SUBSURFACE_IOR_SHADER{ANIM OFF;}
	}
	
	GROUP BUMP
	{
		LONG BUMP_TYPE
		{
			CYCLE
			{
				BUMP_MAP;
				NORMAL_MAP_DIRECTX;
				NORMAL_MAP_OPENGL;
				DISPLACEMENT_0;
				DISPLACEMENT_5;
			}
		}
		SHADERLINK BUMP_VALUE{ANIM OFF;}
		SEPARATOR { LINE; }

		REAL BUMP_INTENSITY{ANIM OFF; MIN 0; MAX 150; CUSTOMGUI REALSLIDER;}
	}
	
	INCLUDE Massign;

}