CONTAINER dl_sky
{
	NAME dl_sky;

	GROUP SHADER_GROUP
	{
		
		REAL SKY_INTENSITY{MIN 0; MAX 10; MINSLIDER 0; MAXSLIDER 10; STEP 0.05; CUSTOMGUI REALSLIDER;}
		SHADERLINK SKY_INTENSITY_SHADER{ANIM OFF;}

		REAL SKY_TURBIDITY{MIN 0; MAX 10; MINSLIDER 0; MAXSLIDER 10; STEP 0.05; CUSTOMGUI REALSLIDER;}
		COLOR SKY_GROUND_COLOR{}
		STATICTEXT LINE1 {ANIM OFF;}
		
		REAL SKY_ELEVATION{MIN 0; MAX 90; MINSLIDER 0; MAXSLIDER 90; STEP 0.450; CUSTOMGUI REALSLIDER;}
		REAL SKY_AZIMUTH{MIN 0; MAX 360; MINSLIDER 0; MAXSLIDER 360; STEP 1.8; CUSTOMGUI REALSLIDER;}
		STATICTEXT LINE2 {ANIM OFF;}

		COLOR SKY_TINT{}
		COLOR SKY_SUN_TINT{}
		REAL SKY_SUN_SIZE{MIN 0; MAX 30; MINSLIDER 0; MAXSLIDER 30; STEP 0.15; CUSTOMGUI REALSLIDER;}
		STATICTEXT LINE3 {ANIM OFF;}

		BOOL SKY_DRAW_SUN_DISK{ANIM OFF;}
		BOOL SKY_DRAW_GROUND{ANIM OFF;}
	
	}

}

