CONTAINER Oblendmaterial
{
	NAME Oblendmaterial;
	INCLUDE Obase;

	GROUP SHADER_GROUP
	{
		DEFAULT 1;
		LINK SHADER_A{ANIM OFF;}
		REAL BLEND_STRENGTH{UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		LINK BLEND_STRENGTH_SHADER{ANIM OFF;}
		LINK SHADER_B{ANIM OFF;}
	}
	
}
