#ifndef _XNORMALDISPLACEMENTSHADER_H_
#define _XNORMALDISPLACEMENTSHADER_H_

enum
{
	DISPLACEMENT_GROUP			= 1000,
	DISPLACEMENT_HEIGHT			=1001,
	DISPLACEMENT_STRENGTH			=1002,
	DISPLACEMENT_STRENGTH_SHADER		=1003,
	DISPLACEMENT_SCALARZERO			=1004
	
	
};
#endif