CONTAINER Xrange
{
	NAME Xrange;

	GROUP RANGE_GROUP
	{
		DEFAULT 1;
		SHADERLINK INPUT_SHADER {ANIM OFF;}
		REAL IN_MIN {CUSTOMGUI REALSLIDER; MINSLIDER 0; MAXSLIDER 1; STEP 0.01;}
		REAL IN_MAX {CUSTOMGUI REALSLIDER;MINSLIDER 0; MAXSLIDER 1;STEP 0.01;}
		REAL OUT_MIN {CUSTOMGUI REALSLIDER;MINSLIDER 0; MAXSLIDER 1;STEP 0.01;}
		REAL OUT_MAX {CUSTOMGUI REALSLIDER;MINSLIDER 0; MAXSLIDER 1;STEP 0.01;}

		
		
	}
	
}
