CONTAINER Xstandardshader
{
	NAME Xstandardshader;

	//INCLUDE Xbase;

	GROUP COATING_GROUP
	{
		BOOL COATING_ON {ANIM OFF;}
		SEPARATOR { LINE; }
		COLOR COATING_COLOR {}
		SHADERLINK COATING_COLOR_SHADER {ANIM OFF;}
		SEPARATOR { LINE; }
		
		COLOR COATING_TRANSMITTANCE {}
		SHADERLINK COATING_TRANSMITTANCE_SHADER {ANIM OFF;}
		SEPARATOR { LINE; }
		REAL COATING_THICKNESS {UNIT METER; MINEX; MIN 0.0;}
		SEPARATOR { LINE; }
		
		REAL COATING_ROUGHNESS{UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		SHADERLINK COATING_ROUGHNESS_SHADER{ANIM OFF;}
		SEPARATOR { LINE; }
		REAL COATING_FR{UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}

	}
	GROUP DIFFUSE_GROUP
	{
		DEFAULT 1;
		REAL DIFFUSE_WEIGHT{UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		SEPARATOR { LINE; }
		COLOR DIFFUSE_COLOR {}
		SHADERLINK DIFFUSE_COLOR_SHADER {ANIM OFF;}
		SEPARATOR { LINE; }
		REAL DIFFUSE_ROUGHNESS {UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		SHADERLINK DIFFUSE_ROUGHNESS_SHADER {ANIM OFF;}


	}
	GROUP SPECULAR_GROUP
	{
		
		REAL SPECULAR_WEIGHT{UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		SEPARATOR { LINE; }
		COLOR SPECULAR_COLOR {}
		SHADERLINK SPECULAR_COLOR_SHADER {ANIM OFF;}
		SEPARATOR { LINE; }
		REAL SPECULAR_ROUGHNESS{UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		SHADERLINK	SPECULAR_ROUGHNESS_SHADER {ANIM OFF;}
		SEPARATOR { LINE; }
		REAL SPECULAR_FR{UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		SEPARATOR { LINE; }
		REAL SPECULAR_ANISOTROPY{ STEP 0.01; MINSLIDER -4; MAXSLIDER 4; CUSTOMGUI REALSLIDER;}
		SHADERLINK SPECULAR_ANISOTROPY_SHADER {ANIM OFF;}
		SEPARATOR { LINE; }
		VECTOR SPECULAR_ANISOTROPY_DIRECTION{MIN -1; MAX 1;}
		SHADERLINK SPECULAR_ANISOTROPY_DIRECTION_SHADER {ANIM OFF;}
	}

	GROUP EMISSION_GROUP
	{
		BOOL EMISSION_ON {ANIM OFF;}
		SEPARATOR { LINE; }
		REAL EMISSION_WEIGHT{UNIT PERCENT; MIN 0; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		SEPARATOR { LINE; }

		COLOR EMISSION_COLOR {}
		SHADERLINK EMISSION_COLOR_SHADER {ANIM OFF;}
	
		
	}

}