CONTAINER Odirectionallight
{
	NAME Odirectionallight;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		COLOR DIRECTIONAL_LIGHT_COLOR{ANIM OFF;}
		SHADERLINK DIRECTIONAL_LIGHT_COLOR_SHADER{ANIM OFF;}
		REAL DIRECTIONAL_LIGHT_INTENSITY {UNIT PERCENT; MIN 0; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		SHADERLINK DIRECTIONAL_LIGHT_INTENSITY_SHADER {ANIM OFF;}
		REAL DIRECTIONAL_LIGHT_EXPOSURE {MINSLIDER -5.0; MAXSLIDER 5.0; STEP 0.1; CUSTOMGUI REALSLIDER;}
		REAL DIRECTIONAL_LIGHT_ANGULAR_DIAMETER {MIN 0; MINSLIDER 0; MAXSLIDER 360; MAX 360; CUSTOMGUI REALSLIDER;}
		
	
		GROUP DIRECTIONAL_LIGHT_CONTRIBUTION
		{
			DEFAULT 1;
			REAL DIRECTIONAL_LIGHT_DIFFUSE {MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			REAL DIRECTIONAL_LIGHT_SPECULAR {MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			REAL DIRECTIONAL_LIGHT_HAIR {MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			REAL DIRECTIONAL_LIGHT_VOLUME {MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		}
	}
}
