#ifndef _Odirectionallight_H_
#define _Odirectionallight_H_

enum
{
	DIRECTIONAL_LIGHT_COLOR=1000,
	DIRECTIONAL_LIGHT_COLOR_SHADER,
	DIRECTIONAL_LIGHT_INTENSITY,
	DIRECTIONAL_LIGHT_INTENSITY_SHADER,
	DIRECTIONAL_LIGHT_ANGULAR_DIAMETER,
	DIRECTIONAL_LIGHT_EXPOSURE,
	DIRECTIONAL_LIGHT_CONTRIBUTION,
	DIRECTIONAL_LIGHT_DIFFUSE,
	DIRECTIONAL_LIGHT_SPECULAR,
	DIRECTIONAL_LIGHT_HAIR,
	DIRECTIONAL_LIGHT_VOLUME,

	DUMMY_VALUE
};

#endif