#ifndef _Oenvironmentlight_H_
#define _Oenvironmentlight_H_

enum
{
	ENVIRONMENT_TEXTURE		= 1000,
	ENVIRONMENT_TEXTURE_COLORSPACE,
	ENVIRONMENT_TEXTURE_COLORSPACE_LINEAR,
	ENVIRONMENT_TEXTURE_COLORSPACE_SRGB,
	ENVIRONMENT_INTENSITY,			
	ENVIRONMENT_TINT,			
	ENVIRONMENT_EXPOSURE,
	ENVIRONMENT_SEEN_BY_CAMERA,
	ENVIRONMENT_ANGLE
};

#endif