CONTAINER Oenvironmentlight
{
	NAME Oenvironmentlight;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
	
		
		COLOR ENVIRONMENT_TINT   {}

		REAL ENVIRONMENT_INTENSITY	{UNIT PERCENT; MIN 0; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		REAL ENVIRONMENT_EXPOSURE {MINSLIDER -6.0; MAXSLIDER 6.0; CUSTOMGUI REALSLIDER;}

		FILENAME ENVIRONMENT_TEXTURE	   {}
		LONG ENVIRONMENT_TEXTURE_COLORSPACE{ CYCLE{ENVIRONMENT_TEXTURE_COLORSPACE_LINEAR; ENVIRONMENT_TEXTURE_COLORSPACE_SRGB;}}
		SEPARATOR { LINE; }
		REAL ENVIRONMENT_ANGLE{UNIT DEGREE; MIN 0; MAX 360;}
		
		SEPARATOR { LINE; }

		BOOL ENVIRONMENT_SEEN_BY_CAMERA{}
	}
}
