CONTAINER Olightcard
{
	NAME Olightcard;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		COLOR LIGHTCARD_COLOR{ANIM OFF;}
		SHADERLINK LIGHTCARD_COLOR_SHADER{ANIM OFF;}
		REAL LIGHTCARD_INTENSITY {UNIT PERCENT; MIN 0; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		SHADERLINK LIGHTCARD_INTENSITY_SHADER {ANIM OFF;}
		REAL LIGHTCARD_EXPOSURE {MINSLIDER -6.0; MAXSLIDER 6.0; CUSTOMGUI REALSLIDER;}
		REAL LIGHTCARD_SPREAD {MINSLIDER -6.0; MAXSLIDER 6.0; CUSTOMGUI REALSLIDER;}
		
		LONG LIGHTCARD_DECAY
		{
			ANIM OFF;
			CYCLE
			{
				LIGHTCARD_DECAY_NODECAY;
				LIGHTCARD_DECAY_LINEAR;
				LIGHTCARD_DECAY_QUADRATIC;
				LIGHTCARD_DECAY_CUBIC;
			}
		}
		
		BOOL LIGHTCARD_NORMALIZE {ANIM OFF;}
		BOOL LIGHTCARD_SEEN_BY_CAMERA {ANIM OFF;}
		BOOL LIGHTCARD_TWO_SIDED {ANIM OFF;}
		BOOL LIGHTCARD_PRELIT {ANIM OFF;}
		
		LONG LIGHTCARD_SHAPE
		{
			ANIM OFF;
			CYCLE
			{
				LIGHTCARD_SHAPE_RECTANGLE;
				LIGHTCARD_SHAPE_DISC;
				LIGHTCARD_SHAPE_SPHERE;
				LIGHTCARD_SHAPE_CYLINDER;
			}
		}
		GROUP LIGHTCARD_CONTRIBUTION
		{
			DEFAULT 1;
			REAL LIGHTCARD_DIFFUSE {MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			REAL LIGHTCARD_SPECULAR {MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			REAL LIGHTCARD_HAIR {MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			REAL LIGHTCARD_VOLUME {MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		}

		REAL LIGHTCARD_WIDTH	   { UNIT METER; MIN 0.0; }
		REAL LIGHTCARD_HEIGHT	   { UNIT METER; MIN 0.0; }
		REAL LIGHTCARD_ZLENGTH	   { UNIT METER; MIN 0.0; HIDDEN; }

	
		//BOOL LIGHTCARD_SEEN_BY_CAMERA{ ANIM OFF;}

	}
}
