#ifndef _Olightcard_H_
#define _Olightcard_H_

enum
{
	LIGHTCARD_WIDTH			= 1000,
	LIGHTCARD_HEIGHT,			
	LIGHTCARD_ZLENGTH,			
	LIGHTCARD_COLOR,		
	LIGHTCARD_COLOR_SHADER,
	LIGHTCARD_INTENSITY,	
	LIGHTCARD_INTENSITY_SHADER,	
	LIGHTCARD_EXPOSURE,
	LIGHTCARD_SPREAD,	
	LIGHTCARD_TWO_SIDED,
	LIGHTCARD_NORMALIZE,
	LIGHTCARD_PRELIT,
	LIGHTCARD_CONTRIBUTION,	
	LIGHTCARD_DIFFUSE,
	LIGHTCARD_SPECULAR,
	LIGHTCARD_HAIR,
	LIGHTCARD_VOLUME,
	
	LIGHTCARD_SAMPLES,		
	LIGHTCARD_TEXTURE,	
	LIGHTCARD_ALPHA,	
	LIGHTCARD_SEEN_BY_CAMERA,
	
	LIGHTCARD_SHAPE,
	LIGHTCARD_SHAPE_RECTANGLE,
	LIGHTCARD_SHAPE_DISC,
	LIGHTCARD_SHAPE_SPHERE,
	LIGHTCARD_SHAPE_CYLINDER,
	
	LIGHTCARD_DECAY,
	LIGHTCARD_DECAY_NODECAY=0,
	LIGHTCARD_DECAY_LINEAR=1,
	LIGHTCARD_DECAY_QUADRATIC=2,
	LIGHTCARD_DECAY_CUBIC=3,
	DUMMY_VALUE
};

#endif