CONTAINER Opointlight
{
	NAME Opointlight;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		COLOR POINTLIGHT_COLOR	   {}
		REAL POINTLIGHT_INTENSITY	{UNIT PERCENT; MIN 0; 		MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		REAL POINTLIGHT_EXPOSURE {MINSLIDER -6.0; MAXSLIDER 6.0; CUSTOMGUI REALSLIDER;}
		
		SEPARATOR { LINE; }
	
		REAL POINTLIGHT_RADIUS	   { UNIT METER; MIN 0.0; }

		SEPARATOR { LINE; }

		BOOL POINTLIGHT_SEEN_BY_CAMERA{ ANIM OFF;}
	}
}
