CONTAINER Ospherelight
{
	NAME Ospherelight;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		COLOR SPHERELIGHT_COLOR	   {}
		REAL SPHERELIGHT_INTENSITY	{UNIT PERCENT; MIN 0; 		MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}

		SEPARATOR { LINE; }
	
		REAL SPHERELIGHT_RADIUS	   { UNIT METER; MIN 0.0; }

		SEPARATOR { LINE; }


	}
}
